version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.5.0
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install Dependencies
                command: npm install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Build Documentation
                command: npm run docs:build
            - run:
                name: Deploy Documentation
                command: |
                    git config --global user.email "support@secanis.ch"
                    git config --global user.name "CircleCI"
                    git config --global push.default matching
                    git add --all
                    git commit -m "Deployment Bot - Auto builded docs [ci skip]"
                    git push --set-upstream origin gh-pages